#!/bin/bash
# Calculates the average size on disk of the pgdbs in the given directory (give it ptools-local/pgdbs/user or equivalent), with and without the data directories

if [[ -z $1 ]]; then
	pgdb_dir=.
else
	pgdb_dir=$1
fi

pgdb_count=0
pgdb_count_nd=0
pgdb_total=0
for pgdb in $(ls --color=never $pgdb_dir); do
	if [[ -e $pgdb/default-version ]]; then
		ver=$(cat $pgdb/default-version)
		if [[ -e $pgdb/$ver ]]; then
			pgdb_size=$(du -sb $pgdb/$ver | cut -d '	' -f 1)
			data_size=0
			if [[ -e $pgdb/$ver/data ]]; then
				data_size=$(du -sb $pgdb/$ver/data | cut -d '	' -f 1)
			fi
			pgdb_count=$(($pgdb_count+1))
			pgdb_total=$(($pgdb_total+$pgdb_size))
			pgdb_total_nd=$(($pgdb_total_nd+$pgdb_size-$data_size))
		fi
	fi
	echo -n "$pgdb_count"
done
echo "Average (with data): $(($pgdb_total/$pgdb_count))"
echo "Average (without data): $(($pgdb_total_nd/$pgdb_count))"
