#!/bin/bash
# Installs all the perl modules in perl_modules/modlist.txt in order

if [[ -z $PMN_PERL_MODS ]]; then
	echo '$PMN_PERL_MODS variable is not set. Please source pmn-environment.sh before running this script'
	exit 1
fi

cd $PMN_PERL_MODS

while IFS= read -r line; do
    if ! ./install-module $line; then
		exit 1
	fi
done < modlist.txt
