#!/bin/bash
# Installs all the perl modules in perl_modules/modlist.txt in order

if [[ -z $perl_mods ]]; then
	echo '$perl_mods variable is not set. Please source pmn-environment.sh before running this script'
	exit 1
fi

cd $perl_mods

while IFS= read -r line; do
    if ! ./install-module $line; then
		exit 1
	fi
done < modlist.txt
